name: Automated Script For SVG

on:
  schedule:
    - cron: '15 20 * * *'  # Every day at 2:00 AM NPT (UTC+5:45)
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-npm-start:
    runs-on: ubuntu-latest

    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      GITHUB_USERNAME: ${{ secrets.USERNAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # disable to use personal token

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run npm start
        run: npm start

      - name: Commit and push changes to dist
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.NAME }}"
          
          git add dist  # safer than dist/*
          
          if ! git diff --cached --quiet; then
            git commit -m "🤖 Auto update dist SVGs"
            git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
            git push origin main
          else
            echo "✅ No changes in dist to commit."
          fi
